#!/usr/bin/env python3
"""Archive helper for iteration rounds: create an archive volume + one changelog index row.

Usage:
  python tools/rollup_round.py --round R27 --date 2026-08-23 --module docs ^
      --summary "one-line conclusion" --detail path/to/detail.md

Behavior:
  1. Write --detail into docs/04-workflow/archive/{date}-{round}.md (with a header; skip if exists);
  2. Insert one row at the top of the changelog.md ledger table, linking to the new archive.
"""

import argparse
import subprocess
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = next(p for p in (Path(__file__).resolve(), *Path(__file__).resolve().parents) if (p / "README.md").is_file())
ARCH = ROOT / "docs" / "04-workflow" / "archive"
CL = (ROOT / "docs" / "04-workflow" / "changelog.md") if (ROOT / "docs" / "04-workflow" / "changelog.md").is_file() else ROOT / "CHANGELOG.md"

NOTE = (
    "> Full iteration records (archive volumes of the changelog ledger). Not read daily; "
    "archaeology enters via `../changelog.md`.\n"
    "> Generated by tools/rollup_round.py.\n"
)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--round", required=True, help="round id, e.g. R27")
    ap.add_argument("--date", required=True, help="date, e.g. 2026-08-23")
    ap.add_argument("--module", required=True, help="module name")
    ap.add_argument("--summary", required=True, help="one-line conclusion")
    ap.add_argument("--detail", required=True, help="path to this round's full Markdown detail")
    args = ap.parse_args()

    r = args.round.upper()
    fname = f"{args.date}-{r.lower()}.md"
    out = ARCH / fname
    if out.exists():
        print(f"already exists, skipped: {fname}")
    else:
        detail = Path(args.detail).read_text(encoding="utf-8")
        out.write_text(f"# {r} · {args.module}（{args.date}）\n\n{NOTE}\n{detail.rstrip()}\n", encoding="utf-8")
        print(f"archive written: {out.relative_to(ROOT)}")

    text = CL.read_text(encoding="utf-8")
    row = f"| {r} | {args.date[5:]} | {args.module} | {args.summary} | [{r.lower()}](archive/{fname}) |"
    sep = "| --- | --- | --- | --- | --- |"
    if sep in text:
        text = text.replace(sep, sep + "\n" + row, 1)
    else:
        text += f"\n| Round | Date | Module | Conclusion | Archive |\n{sep}\n{row}\n"
    CL.write_text(text, encoding="utf-8")
    print(f"changelog row inserted: {row}")

    # Keep the derived project home current at the iteration boundary.  The
    # renderer is local and deterministic; a missing/legacy renderer must not
    # prevent the ledger close-out.
    renderer = ROOT / "tools" / "render_project_home.py"
    if renderer.is_file():
        try:
            subprocess.run([sys.executable, str(renderer)], cwd=ROOT, check=True)
            print("static project home regenerated: status.html")
        except (OSError, subprocess.CalledProcessError) as exc:
            print(f"warning: static project home was not regenerated ({exc})")


if __name__ == "__main__":
    main()
