#!/usr/bin/env python3
"""Generate root llms.txt: a machine-readable index of docs (for LLM tools/crawlers).

Usage:
  python tools/gen_llms_txt.py [--name "project"]

Rules:
  - skip archive/ and _archive/ (archaeology volumes stay out of the index);
  - each .md uses its first `# ` heading as the one-line description;
  - grouped by 00-system / 01-product / 02-technical / 03-reference / 04-workflow;
  - title defaults to the README's first H1, override with --name;
  - regenerate after doc-structure changes.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = next(p for p in (Path(__file__).resolve(), *Path(__file__).resolve().parents) if (p / "README.md").is_file())
DOCS = ROOT / "docs"
LLMS = ROOT / "llms.txt"
SKIP_PARTS = {"archive", "_archive"}
GROUPS = ["00-system", "01-product", "02-technical", "03-reference", "04-workflow"]
HEADING_RE = re.compile(r"^#\s+(.+)$", re.M)


def _desc(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return ""
    m = HEADING_RE.search(text)
    return m.group(1).strip() if m else ""


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate llms.txt")
    ap.add_argument("--name", default=None, help="index title (default: README's first H1)")
    args = ap.parse_args()

    files = sorted(
        (p for p in DOCS.rglob("*.md") if not any(part in SKIP_PARTS for part in p.parts)),
        key=lambda p: p.as_posix(),
    )
    title = args.name
    if not title:
        m = HEADING_RE.search((ROOT / "README.md").read_text(encoding="utf-8"))
        title = m.group(1).strip() if m else ROOT.name
    lines = [
        f"# {title}",
        "",
        "> Machine-readable doc index (generated by tools/gen_llms_txt.py; regenerate after doc changes).",
        "",
        "## Project entry",
        "",
        "- [README.md](README.md): project overview",
        "- [AGENTS.md](AGENTS.md): agent startup contract + module routing",
    ]
    if (ROOT / "README.zh-CN.md").exists():
        lines.append("- [README.zh-CN.md](README.zh-CN.md): 中文说明 / Chinese guide")
    for rel, desc in (
        ("NOW.md", "current product focus / blockers / next"),
        ("CHANGELOG.md", "one-line iteration ledger"),
        ("docs/04-workflow/NOW.md", "current focus / blockers / next"),
        ("docs/04-workflow/changelog.md", "one-line iteration ledger"),
    ):
        if (ROOT / rel).exists():
            lines.append(f"- [{Path(rel).name}]({rel}): {desc}")
    lines.append("")
    root_docs = [p for p in files if len(p.relative_to(ROOT).parts) == 2]
    if root_docs:
        lines.append("## Project docs")
        lines.append("")
        for p in root_docs:
            rel = p.relative_to(ROOT).as_posix()
            desc = _desc(p)
            lines.append(f"- [{p.name}]({rel}): {desc}" if desc else f"- [{p.name}]({rel})")
        lines.append("")
    for group in GROUPS:
        group_files = [
            p for p in files
            if len(p.relative_to(ROOT).parts) > 2 and p.relative_to(ROOT).parts[1] == group
        ]
        if not group_files:
            continue
        lines.append(f"## {group}")
        lines.append("")
        for p in group_files:
            rel = p.relative_to(ROOT).as_posix()
            desc = _desc(p)
            lines.append(f"- [{p.name}]({rel}): {desc}" if desc else f"- [{p.name}]({rel})")
        lines.append("")
    LLMS.write_text("\n".join(lines), encoding="utf-8")
    print(f"llms.txt generated: {LLMS.relative_to(ROOT)} ({len(files)} docs indexed)")


if __name__ == "__main__":
    main()
